---
title: "STAT 545A Homework 1"
author: Junbin ZHANG
date: Sept 7, 2018
output: github_document
---

# Get the Gapminder data
```{r}
## load gapminder
library(gapminder)
```

# Meet the `gapminder` data frame of "tibble"

```{r}
## display the structure of gapminder
str(gapminder)

## load tidyverse
library(tidyverse)

## display class of gapminder
class(gapminder)

## display gapminder as tibble
gapminder

## print head of gapminder
head(gapminder)

## print tail of gapminder
tail(gapminder)

## turn iris into tibble
as_tibble(iris)

## print column names
names(gapminder)

## print number of columns
ncol(gapminder)

## print length of gapminder
length(gapminder)

## print dimension of gapminder
dim(gapminder)

## print number of rows
nrow(gapminder)

## display statistical overview (summary) of gapminder
summary(gapminder)

## plot lifeExp vs year
plot(lifeExp ~ year, gapminder)

## plot lifeExp vs gdpPercap
plot(lifeExp ~ gdpPercap, gapminder)

## plot lifeExp vs log(gdpPercap)
plot(lifeExp ~ log(gdpPercap), gapminder)

## display the structure of gapminder again
str(gapminder)
```

# Look at variables inside a data frame
```{r}
## print head of lifeExp
head(gapminder$lifeExp)

## display summary of lifeExp
summary(gapminder$lifeExp)

## plot histogram of lifeExp
hist(gapminder$lifeExp)

## display summary of year
summary(gapminder$year)

## display year as a table
table(gapminder$year)

## print class of continent
class(gapminder$continent)

## display summary of continent
summary(gapminder$continent)

## print levels of continent
levels(gapminder$continent)

## print number of levels
nlevels(gapminder$continent)

## display summary of continent
str(gapminder$continent)

## display continent as a table
table(gapminder$continent)

## plot continent as a barplot
barplot(table(gapminder$continent))

## explore ggplot2
# initialization
p <- ggplot(filter(gapminder, continent != "Oceania"),
            aes(x = gdpPercap, y = lifeExp))
# log the x axis
p <- p + scale_x_log10()
# scatterplot
p + geom_point()
# color map
p + geom_point(aes(color = continent))
# other explorations of ggplot2
p + geom_point(alpha = (1/3), size = 3) + geom_smooth(lwd = 3, se = FALSE)
p + geom_point(alpha = (1/3), size = 3) + facet_wrap(~ continent) +
  geom_smooth(lwd = 1.5, se = FALSE)
```